init:
  # clear_output_directories: true

Clean:
  output_directory: 'testdata/solr_20150320/clean'
    
Identify:
  identifiers:
    - lib/configs/rdf_identifier.yaml
    - lib/configs/ogc_identifier.yaml
    - lib/configs/opensearch_identifier.yaml
    - lib/configs/iso_identifier.yaml
    - lib/configs/oaipmh_identifier.yaml
    - lib/configs/thredds_identifier.yaml
    - lib/configs/extra_identifier.yaml
    - lib/configs/dif_identifier.yaml
    - lib/configs/fgdc_identifier.yaml
    - lib/configs/atom_identifier.yaml
    - lib/configs/wsdl_identifier.yaml
    - lib/configs/wadl_identifier.yaml
  output_directory: 'testdata/solr_20150320/identify'
